# Generated by Django 2.2.6 on 2019-12-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
