# Generated by Django 2.2.6 on 2019-12-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PPE',
        ),
    ]
