# Generated by Django 2.2.6 on 2019-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0004_experiment_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppe',
            name='cat_type',
        ),
        migrations.AddField(
            model_name='ppe',
            name='ppe_type',
            field=models.IntegerField(choices=[('อุปกรณ์ป้องกันศีรษะ', 'Head Protection Equipment'), ('อุปกรณ์ป้องกันใบหน้าและตา', 'Eye and face protection equipment'), ('อุปกรณ์ป้องกันหู', 'Ear protection equipment'), ('อุปกรณ์ป้องกันการหายใจ', 'Respiratory protection equipment'), ('อุปกรณ์ป้องกันลำตัว', 'Body Protection Equipment'), ('อุปกรณ์ป้องกันมือ', 'Hand Protection Equipment'), ('อุปกรณ์ป้องกันเท้า', 'Foot Protection Equipment')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
