# Generated by Django 2.2.6 on 2019-12-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0005_auto_20191204_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppe',
            name='ppe_type',
            field=models.CharField(choices=[('อุปกรณ์ป้องกันศีรษะ', 'Head Protection Equipment'), ('อุปกรณ์ป้องกันใบหน้าและตา', 'Eye and face protection equipment'), ('อุปกรณ์ป้องกันหู', 'Ear protection equipment'), ('อุปกรณ์ป้องกันการหายใจ', 'Respiratory protection equipment'), ('อุปกรณ์ป้องกันลำตัว', 'Body Protection Equipment'), ('อุปกรณ์ป้องกันมือ', 'Hand Protection Equipment'), ('อุปกรณ์ป้องกันเท้า', 'Foot Protection Equipment')], max_length=50),
        ),
    ]
