# Generated by Django 2.2.6 on 2019-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0006_auto_20191204_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_1',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_2',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_3',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_4',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_5',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_6',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_7',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_8',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='ghs_name_9',
            field=models.CharField(choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
