# Generated by Django 2.2.6 on 2019-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0007_auto_20191204_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_2',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_3',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_4',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_5',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_6',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_7',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_8',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_9',
            field=models.CharField(blank=True, choices=[('สารไวไฟ', 'Flame'), ('สารออกซิไดซ์', 'Flame Over Circle'), ('วัตถุระเบิด', 'Exploding Bomb'), ('ก๊าซบรรจุภายใต้ความดัน', 'Gas Cylinder'), ('สารกัดกร่อน', 'Corrosion'), ('พิษเฉียบพลัน', 'Skull & Crossbones'), ('อันตรายต่อสุขภาพ', 'Health Hazard'), ('ระวัง', 'Exclamation Mark'), ('อันตรายต่อิ่งแวดล้อม', 'Environment')], max_length=50),
        ),
    ]
