# Generated by Django 2.2.6 on 2020-01-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0012_auto_20200107_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_2',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_3',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_4',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_5',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_6',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_7',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_8',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_name_9',
            field=models.CharField(choices=[('สารไวไฟ', 'สารไวไฟ'), ('สารออกซิไดซ์', 'สารออกซิไดซ์'), ('วัตถุระเบิด', 'วัตถุระเบิด'), ('ก๊าซบรรจุภายใต้ความดัน', 'ก๊าซบรรจุภายใต้ความดัน'), ('สารกัดกร่อน', 'สารกัดกร่อน'), ('พิษเฉียบพลัน', 'พิษเฉียบพลัน'), ('อันตรายต่อสุขภาพ', 'อันตรายต่อสุขภาพ'), ('ระวัง', 'ระวัง'), ('อันตรายต่อิ่งแวดล้อม', 'อันตรายต่อิ่งแวดล้อม')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_2',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_3',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_4',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_5',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_6',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_7',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_8',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='ghs_sign_9',
            field=models.ImageField(null=True, upload_to='GHS_SIGN/%Y/%m/%d'),
        ),
    ]
