# Generated by Django 2.2.6 on 2020-01-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu2', '0013_auto_20200107_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='ppe_type',
        ),
        migrations.AddField(
            model_name='experiment',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu2.PPE'),
            preserve_default=False,
        ),
    ]
