# Generated by Django 2.2.6 on 2019-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('การประชุม', 'Meeting'), ('การฝึกอบรม', 'Training'), ('การสัมมนา', 'Seminar'), ('การเสวนา', 'Converse')], max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('detail', models.TextField()),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('locality', models.CharField(max_length=500)),
                ('link', models.TextField(blank=True)),
            ],
        ),
    ]
