# Generated by Django 2.2.6 on 2019-11-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(),
        ),
    ]
