# Generated by Django 2.2.6 on 2019-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu3', '0004_auto_20191119_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
