# Generated by Django 2.2.6 on 2019-11-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu3', '0005_auto_20191119_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.FloatField(),
        ),
    ]
