# Generated by Django 2.2.6 on 2019-11-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu3', '0008_auto_20191119_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='register',
        ),
        migrations.AddField(
            model_name='register',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu3.Event'),
            preserve_default=False,
        ),
    ]
